;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	E6F971B37336C0F9FCE53F895780031E

; File Name   :	th02/MAINE.EXE
; Format      :	MS-DOS executable (EXE)
; Base Address:	0h Range: 0h-FCF0h Loaded length: DE32h
; Entry	Point :	0:0
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

		.286 ; Force the .model directive to create 16-bit default segments...
		.model large maine_02_TEXT
		__LARGE__ equ 1
		.386 ; ... then switch to what we actually need.
		; And yes, we can't move this to an include file for some reason.

include ReC98.inc
include th02/th02.inc

	extern SCOPY@:proc
	extern _execl:proc

; ===========================================================================

; Segment type:	Pure code
_TEXT		segment	word public 'CODE' use16
		assume cs:_TEXT
		assume es:nothing, ds:_DATA, fs:nothing, gs:nothing

include libs/master.lib/bfnt_entry_pat.asm
include libs/master.lib/bfnt_extend_header_skip.asm
include libs/master.lib/bfnt_header_read.asm
include libs/master.lib/bfnt_header_analysis.asm
include libs/master.lib/bcloser.asm
include libs/master.lib/bfill.asm
include libs/master.lib/bfnt_palette_set.asm
include libs/master.lib/bgetc.asm
include libs/master.lib/palette_black_in.asm
include libs/master.lib/palette_black_out.asm
include libs/master.lib/bopenr.asm
include libs/master.lib/bread.asm
include libs/master.lib/bseek.asm
include libs/master.lib/bseek_.asm
include libs/master.lib/cutline.asm
include libs/master.lib/dos_axdx.asm
include libs/master.lib/dos_filesize.asm
include libs/master.lib/dos_setvect.asm
include libs/master.lib/egc.asm
include libs/master.lib/egc_shift_down.asm
include libs/master.lib/egc_shift_left.asm
include libs/master.lib/file_append.asm
include libs/master.lib/file_close.asm
include libs/master.lib/file_exist.asm
include libs/master.lib/file_read.asm
include libs/master.lib/file_ropen.asm
include libs/master.lib/file_seek.asm
include libs/master.lib/file_size.asm
include libs/master.lib/file_write.asm
include libs/master.lib/dos_close.asm
include libs/master.lib/dos_ropen.asm
include libs/master.lib/grcg_boxfill.asm
include libs/master.lib/grcg_line.asm
include libs/master.lib/grcg_setcolor.asm
include libs/master.lib/gaiji_backup.asm
include libs/master.lib/gaiji_entry_bfnt.asm
include libs/master.lib/gaiji_putca.asm
include libs/master.lib/gaiji_putsa.asm
include libs/master.lib/gaiji_read.asm
include libs/master.lib/gaiji_write.asm
include libs/master.lib/graph_400line.asm
include libs/master.lib/graph_clear.asm
include libs/master.lib/graph_copy_page.asm
include libs/master.lib/graph_extmode.asm
include libs/master.lib/graph_gaiji_putc.asm
include libs/master.lib/graph_gaiji_puts.asm
include libs/master.lib/graph_pi_free.asm
include libs/master.lib/graph_pi_load_pack.asm
include libs/master.lib/graph_pack_put_8.asm
include libs/master.lib/key_sense.asm
include libs/master.lib/over_put_8.asm
include libs/master.lib/palette_show.asm
include libs/master.lib/pfclose.asm
include libs/master.lib/pfgetc.asm
include libs/master.lib/pfread.asm
include libs/master.lib/pfrewind.asm
include libs/master.lib/pfseek.asm
include libs/master.lib/palette_entry_rgb.asm
include libs/master.lib/rottbl.asm
include libs/master.lib/smem_release.asm
include libs/master.lib/smem_wget.asm
include libs/master.lib/text_clear.asm
include libs/master.lib/vsync.asm
include libs/master.lib/vsync_wait.asm
include libs/master.lib/palette_white_in.asm
include libs/master.lib/palette_white_out.asm
include libs/master.lib/hmem_lallocate.asm
include libs/master.lib/mem_assign_dos.asm
include libs/master.lib/mem_assign.asm
include libs/master.lib/memheap.asm
include libs/master.lib/mem_unassign.asm
include libs/master.lib/super_entry_pat.asm
include libs/master.lib/super_entry_at.asm
include libs/master.lib/super_entry_bfnt.asm
include libs/master.lib/pfint21.asm
		db 0
include th02/formats/pfopen.asm
include libs/master.lib/pf_str_ieq.asm
_TEXT		ends

; ===========================================================================

; Segment type:	Pure code
maine_01_TEXT	segment	byte public 'CODE' use16
		assume cs:maine_01_TEXT
		;org 3
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
;void pascal load_end_txt (char* fn)
load_end_txt	proc near

@@size		= word ptr -2
@@fn		= dword	ptr  4

		enter	2, 0
		pushd	[bp+@@fn]
		call	file_ropen
		call	file_size
		mov	[bp+@@size], ax
		push	ds
		push	offset end_buf
		push	ax
		call	file_read
		call	file_close
		leave
		retn	4
load_end_txt	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
;void pascal gaiji_score_put (int x, int y, long? value)
gaiji_score_put	proc near

var_9		= byte ptr -9
var_8		= dword	ptr -8
var_4		= dword	ptr -4
@@value		= dword	ptr  4
@@y		= word ptr  8
@@x		= word ptr  0Ah

		enter	0Ah, 0
		push	si
		push	di
		mov	di, gb_0_
		mov	[bp+var_4], 10000000
		mov	[bp+var_9], 0
		xor	si, si
		jmp	short loc_9638
; ---------------------------------------------------------------------------

loc_95E4:
		mov	eax, [bp+@@value]
		cdq
		idiv	[bp+var_4]
		mov	ebx, 10
		cdq
		idiv	ebx
		mov	[bp+var_8], edx
		mov	eax, [bp+var_4]
		cdq
		idiv	ebx
		mov	[bp+var_4], eax
		mov	ax, word ptr [bp+var_8]
		add	ax, gb_0_
		mov	di, ax
		cmp	[bp+var_8], 0
		jz	short loc_961D
		mov	[bp+var_9], 1

loc_961D:
		cmp	[bp+var_9], 0
		jz	short loc_9637
		mov	ax, si
		shl	ax, 4
		add	ax, [bp+@@x]
		call	graph_gaiji_putc pascal, ax, [bp+@@y], di, 15

loc_9637:
		inc	si

loc_9638:
		cmp	si, 8
		jl	short loc_95E4
		pop	di
		pop	si
		leave
		retn	8
gaiji_score_put	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
;void pascal graph_putsa_fx_with_typing(int x, int y. int len, char* str, int delay)
graph_putsa_fx_with_typing	proc near

@@buf		= byte ptr -50h
@@delay		= word ptr  4
@@str		= dword	ptr  6
@@len		= word ptr  0Ah
@@y		= word ptr  0Ch
@@x		= word ptr  0Eh

		enter	50h, 0
		push	si
		push	di
		lea	ax, [bp+@@buf]
		push	ss
		push	ax
		push	ds
		push	offset unk_D030
		mov	cx, size unk_D030
		call	SCOPY@
		xor	si, si
		xor	di, di
		jmp	short loc_96C4
; ---------------------------------------------------------------------------

loc_9660:
		call	_input_sense
		les	bx, [bp+@@str]
		add	bx, si
		mov	al, es:[bx]
		mov	[bp+si+@@buf],	al
		inc	si
		mov	bx, word ptr [bp+@@str]
		add	bx, si
		mov	al, es:[bx]
		mov	[bp+si+@@buf],	al
		inc	si
		mov	[bp+si+@@buf],	0
		push	ss
		lea	ax, [bp+@@buf]
		push	ax
		mov	al, text_default_fx
		cbw
		push	ax
		push	[bp+@@y]
		push	[bp+@@x]
		call	_graph_putsa_fx
		add	sp, 0Ah
		cmp	text_force_type_fast, 0
		jz	short @@type_nomal_speed
		cmp	_key_det, 0
		jz	short @@type_nomal_speed
		test	di, 3
		jz	short loc_96C1
		mov	ax, [bp+@@delay]
		mov	bx, 3
		cwd
		idiv	bx
		push	ax
		jmp	short @@type_faster
; ---------------------------------------------------------------------------

@@type_nomal_speed:
		push	[bp+@@delay]

@@type_faster:
		call	frame_delay

loc_96C1:
		add	di, 2

loc_96C4:
		cmp	di, [bp+@@len]
		jl	short loc_9660
		xor	si, si
		jmp	short loc_96EC
; ---------------------------------------------------------------------------

loc_96CD:
		call	_input_sense
		cmp	text_force_type_fast, 0
		jz	short @@type_text_faster
		cmp	_key_det, 0
		jz	short @@type_text_faster
		push	0
		jmp	short @@no_delay
; ---------------------------------------------------------------------------

@@type_text_faster:
		push	2

@@no_delay:
		call	frame_delay
		inc	si

loc_96EC:
		cmp	si, 20
		jl	short loc_96CD
		cmp	text_force_type_fast, 0
		jz	short loc_96FB
		call	sub_9A7E

loc_96FB:
		pop	di
		pop	si
		leave
		retn	0Ch
graph_putsa_fx_with_typing	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_9701	proc far

var_8		= word ptr -8
var_6		= word ptr -6
var_4		= word ptr -4
var_2		= word ptr -2
arg_0		= word ptr  6
arg_2		= word ptr  8
arg_4		= dword	ptr  0Ah

		enter	8, 0
		push	si
		push	di
		mov	ax, [bp+arg_0]
		sar	ax, 3
		mov	dx, [bp+arg_2]
		shl	dx, 6
		add	ax, dx
		mov	dx, [bp+arg_2]
		shl	dx, 4
		add	ax, dx
		mov	si, ax
		xor	di, di
		jmp	loc_97E6
; ---------------------------------------------------------------------------

loc_9724:
		graph_accesspage 1
		les	bx, _VRAM_PLANE_B
		add	bx, si
		mov	ax, es:[bx]
		mov	[bp+var_8], ax
		les	bx, _VRAM_PLANE_R
		add	bx, si
		mov	ax, es:[bx]
		mov	[bp+var_6], ax
		les	bx, _VRAM_PLANE_G
		add	bx, si
		mov	ax, es:[bx]
		mov	[bp+var_4], ax
		les	bx, _VRAM_PLANE_E
		add	bx, si
		mov	ax, es:[bx]
		mov	[bp+var_2], ax
		mov	al, 0
		out	dx, al
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 0
		mov	ax, di
		add	ax, ax
		les	bx, [bp+arg_4]
		add	bx, ax
		mov	ax, es:[bx]
		les	bx, _VRAM_PLANE_B
		add	bx, si
		mov	es:[bx], ax
		call	grcg_off
		mov	ax, di
		add	ax, ax
		les	bx, [bp+arg_4]
		add	bx, ax
		mov	ax, es:[bx]
		and	ax, [bp+var_8]
		les	bx, _VRAM_PLANE_B
		add	bx, si
		or	es:[bx], ax
		mov	ax, di
		add	ax, ax
		les	bx, [bp+arg_4]
		add	bx, ax
		mov	ax, es:[bx]
		and	ax, [bp+var_6]
		les	bx, _VRAM_PLANE_R
		add	bx, si
		or	es:[bx], ax
		mov	ax, di
		add	ax, ax
		les	bx, [bp+arg_4]
		add	bx, ax
		mov	ax, es:[bx]
		and	ax, [bp+var_4]
		les	bx, _VRAM_PLANE_G
		add	bx, si
		or	es:[bx], ax
		mov	ax, di
		add	ax, ax
		les	bx, [bp+arg_4]
		add	bx, ax
		mov	ax, es:[bx]
		and	ax, [bp+var_2]
		les	bx, _VRAM_PLANE_E
		add	bx, si
		or	es:[bx], ax
		add	si, 80
		inc	di

loc_97E6:
		cmp	di, 16
		jl	loc_9724
		pop	di
		pop	si
		leave
		retf
sub_9701	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

text_fadein_effect	proc far

var_60		= byte ptr -60h
arg_0		= word ptr  6
arg_2		= word ptr  8
arg_4		= word ptr  0Ah

		enter	60h, 0
		push	si
		push	di
		lea	ax, [bp+var_60]
		push	ss
		push	ax
		push	ds
		push	offset byte_D080
		mov	cx, 8*12
		call	SCOPY@
		xor	di, di
		jmp	short loc_983D
; ---------------------------------------------------------------------------

loc_980C:
		xor	si, si
		jmp	short loc_9830
; ---------------------------------------------------------------------------

loc_9810:
		mov	ax, di
		shl	ax, 5
		lea	dx, [bp+var_60]
		add	ax, dx
		push	ss
		push	ax
		push	[bp+arg_2]
		mov	ax, si
		shl	ax, 4
		add	ax, [bp+arg_0]
		push	ax
		call	sub_9701
		add	sp, 8
		inc	si

loc_9830:
		cmp	si, [bp+arg_4]
		jl	short loc_9810
		call	frame_delay pascal, 10
		inc	di

loc_983D:
		cmp	di, 3
		jl	short loc_980C
		pop	di
		pop	si
		leave
		retf
text_fadein_effect	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_9846	proc near

var_2		= byte ptr -2
var_1		= byte ptr -1
arg_0		= dword	ptr  4
arg_4		= word ptr  8

		enter	2, 0
		push	si
		push	di
		mov	di, [bp+arg_4]
		mov	si, 100
		mov	[bp+var_2], 0
		xor	cx, cx
		jmp	short loc_98A1
; ---------------------------------------------------------------------------

loc_985A:
		mov	ax, di
		cwd
		idiv	si
		mov	[bp+var_1], al
		cmp	[bp+var_2], 0
		jnz	short loc_986B
		mov	[bp+var_2], al

loc_986B:
		cmp	[bp+var_2], 0
		jnz	short loc_9876
		cmp	cx, 2
		jnz	short loc_9885

loc_9876:
		les	bx, [bp+arg_0]
		add	bx, cx
		mov	al, [bp+var_1]
		add	al, 160
		mov	es:[bx], al
		jmp	short loc_988E
; ---------------------------------------------------------------------------

loc_9885:
		les	bx, [bp+arg_0]
		add	bx, cx
		mov	byte ptr es:[bx], 0CFh 
		
loc_988E:
		mov	al, [bp+var_1]
		cbw
		imul	si
		sub	di, ax
		inc	cx
		mov	bx, 10
		mov	ax, si
		cwd
		idiv	bx
		mov	si, ax

loc_98A1:
		cmp	cx, 3
		jl	short loc_985A
		les	bx, [bp+arg_0]
		add	bx, cx
		mov	byte ptr es:[bx], 0
		pop	di
		pop	si
		leave
		retn	6
sub_9846	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
; egc_quarter_put(int slot)
egc_quarter_put	proc near

var_6		= word ptr -6
var_4		= word ptr -4
var_2		= word ptr -2
arg_0		= word ptr  4

		enter	6, 0
		push	si
		push	di
		cmp	[bp+arg_0], 0
		jnz	short loc_98C5
		xor	ax, ax
		jmp	short loc_98DE
; ---------------------------------------------------------------------------

loc_98C5:
		cmp	[bp+arg_0], 1
		jnz	short loc_98D0
		mov	ax, (320 / 8)
		jmp	short loc_98DE
; ---------------------------------------------------------------------------

loc_98D0:
		cmp	[bp+arg_0], 2
		jnz	short loc_98DB
		mov	ax, (640 * 200) / 8
		jmp	short loc_98DE
; ---------------------------------------------------------------------------

loc_98DB:
		mov	ax, ((640 * 200) + 320) / 8

loc_98DE:
		mov	si, ax
		mov	di, 1F54h;someone please conver to xy cord....
		call	egc_start_copy
		mov	[bp+var_2], 0
		jmp	short loc_9930
; ---------------------------------------------------------------------------

loc_98EF:
		mov	[bp+var_4], 0
		jmp	short loc_9921
; ---------------------------------------------------------------------------

loc_98F6:
		graph_accesspage 1
		les	bx, _VRAM_PLANE_B
		add	bx, si
		mov	ax, es:[bx]
		mov	[bp+var_6], ax
		mov	al, 0
		out	dx, al
		mov	bx, word ptr _VRAM_PLANE_B
		add	bx, di
		mov	ax, [bp+var_6]
		mov	es:[bx], ax
		add	[bp+var_4], 2
		add	si, 2
		add	di, 2

loc_9921:
		cmp	[bp+var_4], (320 / 8)
		jl	short loc_98F6
		inc	[bp+var_2]
		add	di, (320 / 8)
		add	si, (320 / 8)

loc_9930:
		cmp	[bp+var_2], 200
		jl	short loc_98EF
		call	egc_off
		pop	di
		pop	si
		leave
		retn	2
egc_quarter_put	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
; egc_quarter_put_x_y(int x, int y, int slot)
egc_quarter_put_x_y	proc near

var_6		= word ptr -6
var_4		= word ptr -4
var_2		= word ptr -2
arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8

		enter	6, 0
		push	si
		push	di
		cmp	[bp+arg_0], 0
		jnz	short loc_9952
		xor	ax, ax
		jmp	short loc_996B
; ---------------------------------------------------------------------------

loc_9952:
		cmp	[bp+arg_0], 1
		jnz	short loc_995D
		mov	ax, (320 / 8)
		jmp	short loc_996B
; ---------------------------------------------------------------------------

loc_995D:
		cmp	[bp+arg_0], 2
		jnz	short loc_9968
		mov	ax, (640 * 200) / 8
		jmp	short loc_996B
; ---------------------------------------------------------------------------

loc_9968:
		mov	ax, ((640 * 200) + 320) / 8

loc_996B:
		mov	si, ax
		mov	ax, [bp+arg_4]
		sar	ax, 3
		mov	dx, [bp+arg_2]
		shl	dx, 6
		add	ax, dx
		mov	dx, [bp+arg_2]
		shl	dx, 4
		add	ax, dx
		mov	di, ax
		call	egc_start_copy
		mov	[bp+var_2], 0
		jmp	short loc_99D2
; ---------------------------------------------------------------------------

loc_9991:
		mov	[bp+var_4], 0
		jmp	short loc_99C3
; ---------------------------------------------------------------------------

loc_9998:
		graph_accesspage 1
		les	bx, _VRAM_PLANE_B
		add	bx, si
		mov	ax, es:[bx]
		mov	[bp+var_6], ax
		mov	al, 0
		out	dx, al
		mov	bx, word ptr _VRAM_PLANE_B
		add	bx, di
		mov	ax, [bp+var_6]
		mov	es:[bx], ax
		add	[bp+var_4], 2
		add	si, 2
		add	di, 2

loc_99C3:
		cmp	[bp+var_4], (320 / 8)
		jl	short loc_9998
		inc	[bp+var_2]
		add	di, (320 / 8)
		add	si, (320 / 8)

loc_99D2:
		cmp	[bp+var_2], 200
		jl	short loc_9991
		call	egc_off
		pop	di
		pop	si
		leave
		retn	6
egc_quarter_put_x_y	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_99E4	proc near

var_6		= word ptr -6
var_4		= word ptr -4
var_2		= word ptr -2
arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8

		enter	6, 0
		push	si
		push	di
		cmp	[bp+arg_4], 0
		jnz	short loc_99F4
		xor	ax, ax
		jmp	short loc_9A0D
; ---------------------------------------------------------------------------

loc_99F4:
		cmp	[bp+arg_4], 1
		jnz	short loc_99FF
		mov	ax, (320 / 8)
		jmp	short loc_9A0D
; ---------------------------------------------------------------------------

loc_99FF:
		cmp	[bp+arg_4], 2
		jnz	short loc_9A0A
		mov	ax, (640 * 200) / 8
		jmp	short loc_9A0D
; ---------------------------------------------------------------------------

loc_9A0A:
		mov	ax, ((640 * 200) + 320) / 8

loc_9A0D:
		mov	si, ax
		mov	di, 1F54h
		mov	ax, [bp+arg_2]
		imul	ax, 80
		add	si, ax
		call	egc_start_copy
		mov	ax, [bp+arg_2]
		mov	[bp+var_2], ax
		jmp	short loc_9A68
; ---------------------------------------------------------------------------

loc_9A27:
		mov	[bp+var_4], 0
		jmp	short loc_9A59
; ---------------------------------------------------------------------------

loc_9A2E:
		graph_accesspage 1
		les	bx, _VRAM_PLANE_B
		add	bx, si
		mov	ax, es:[bx]
		mov	[bp+var_6], ax
		mov	al, 0
		out	dx, al
		mov	bx, word ptr _VRAM_PLANE_B
		add	bx, di
		mov	ax, [bp+var_6]
		mov	es:[bx], ax
		add	[bp+var_4], 2
		add	si, 2
		add	di, 2

loc_9A59:
		cmp	[bp+var_4], (320 / 8)
		jl	short loc_9A2E
		inc	[bp+var_2]
		add	di, (320 / 8)
		add	si, (320 / 8)

loc_9A68:
		mov	ax, [bp+arg_0]
		add	ax, [bp+arg_2]
		cmp	ax, [bp+var_2]
		jg	short loc_9A27
		call	egc_off
		pop	di
		pop	si
		leave
		retn	6
sub_99E4	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_9A7E	proc near

var_2		= word ptr -2

		enter	2, 0
		push	si
		push	di
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 0
		mov	si, 14Ch
		jmp	short loc_9AC5
; ---------------------------------------------------------------------------

loc_9A94:
		mov	di, 90h
		jmp	short loc_9ABE
; ---------------------------------------------------------------------------

loc_9A99:
		mov	ax, di
		sar	ax, 3
		mov	dx, si
		shl	dx, 6
		add	ax, dx
		mov	dx, si
		shl	dx, 4
		add	ax, dx
		mov	[bp+var_2], ax
		les	bx, _VRAM_PLANE_B
		add	bx, [bp+var_2]
		mov	word ptr es:[bx], -1
		add	di, 10h

loc_9ABE:
		cmp	di, 1F0h
		jl	short loc_9A99
		inc	si

loc_9AC5:
		cmp	si, 15Ch
		jl	short loc_9A94
		call	grcg_off
		pop	di
		pop	si
		leave
		retn
sub_9A7E	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_9AD4	proc near
		push	bp
		mov	bp, sp
		push	si
		call	load_end_txt pascal, ds, offset aEnd3_txt
		call	frame_delay pascal, 30
		call	palette_white_out pascal, 1
		call	_snd_load c, offset aEnding_m, ds, SND_LOAD_SONG
		kajacall	KAJA_SONG_PLAY
		pop	cx
		call	sub_9A7E
		call	palette_white_in pascal, 4
		call	_snd_delay_until_measure stdcall, 5
		pop	cx
		mov	si, 0A0h
		jmp	short loc_9B5C
; ---------------------------------------------------------------------------

loc_9B1B:
		push	si
		push	100
		lea	ax, [si+319]
		push	ax
		push	(299 shl 16) or 4
		call	egc_shift_left
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 0
		lea	ax, [si+312]
		push	ax
		push	100
		lea	ax, [si+319]
		push	ax
		push	299
		call	grcg_boxfill
		call	grcg_off
		call	frame_delay pascal, 1
		sub	si, 4

loc_9B5C:
		cmp	si, 36
		jg	short loc_9B1B
		pop	si
		pop	bp
		retn
sub_9AD4	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_9B64	proc near
		push	bp
		mov	bp, sp
		push	si
		call	load_end_txt pascal, ds, offset aEnd1_txt
		call	_snd_load c, offset aEnd1_m, ds, SND_LOAD_SONG
		kajacall	KAJA_SONG_PLAY
		pop	cx
		mov	PaletteTone, 0
		call	far ptr	palette_show
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd01_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	palette_black_in pascal, 2
		call	frame_delay pascal, 40
		call	egc_quarter_put pascal, 0
		mov	text_default_fx, (15 or 2 shl 4) 
		mov	text_force_type_fast, 1
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf, 6
		call	frame_delay pascal, 20
		call	palette_black_out pascal, 1
		call	egc_quarter_put pascal, 1
		call	palette_black_in pascal, 1
		ENDTEXT_PRINT_MUTIPLE_LINE 1, 3, 6
		call	egc_quarter_put pascal, 2
		ENDTEXT_PRINT_MUTIPLE_LINE 4, 2, 6
		mov	text_default_fx, (6 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 6), 6
		mov	text_default_fx, (15 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 7, 3, 6
		mov	text_default_fx, (6 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 10), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 11), 6
		call	frame_delay pascal, 20
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 12), 6
		xor	si, si
		jmp	short loc_9D10
; ---------------------------------------------------------------------------

loc_9CDE:
		graph_accesspage 0
		call	egc_shift_down pascal, (160 shl 16) or 100, (479 shl 16) or 297, 2
		push	3
		mov	ax, si
		add	ax, ax
		mov	dx, 198
		sub	dx, ax
		push	dx
		push	2
		call	sub_99E4
		call	frame_delay pascal, 1
		inc	si

loc_9D10:
		cmp	si, 100
		jl	short loc_9CDE
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 13), 6
		mov	text_default_fx, (6 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 14, 2, 6
		mov	text_default_fx, (15 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 16, 2, 6
		mov	text_default_fx, (6 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 18, 3, 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 21), 6
		mov	text_default_fx, (6 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 22), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 23), 6
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd02_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	palette_black_out pascal, 2
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.shottype], 0
		jnz	short loc_9E2A
		push	0
		jmp	short loc_9E3B
; ---------------------------------------------------------------------------

loc_9E2A:
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.shottype], 1
		jnz	short loc_9E39
		push	2
		jmp	short loc_9E3B
; ---------------------------------------------------------------------------

loc_9E39:
		push	3

loc_9E3B:
		call	egc_quarter_put
		call	palette_black_in pascal, 2
		mov	text_default_fx, (6 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 24), 6
		mov	text_default_fx, (15 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 25, 2, 6
		mov	text_default_fx, (6 or 2 shl 4)
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.shottype], 0
		jnz	loc_9F22
		ENDTEXT_PRINT_MUTIPLE_LINE 27, 2, 6
		mov	text_default_fx, (15 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 29, 2, 6
		call	egc_quarter_put pascal, 1
		mov	text_default_fx, (6 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 31), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 32), 12
		mov	text_force_type_fast, 0
		push	(144 shl 16 or 332)
		push	44
		push	ds
		push	offset end_buf + (END_LINE_LEN * 33)
		jmp	loc_A092
; ---------------------------------------------------------------------------

loc_9F22:
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.shottype], 1
		jnz	loc_9FD3
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 34), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 35), 6
		mov	text_default_fx, (6 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 36), 6
		mov	text_default_fx, (15 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 37, 2, 6
		mov	text_default_fx, (6 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 39), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 40), 12
		mov	text_force_type_fast, 0
		push	(144 shl 16 or 332)
		push	44
		push	ds
		push	offset end_buf + (END_LINE_LEN * 41)
		jmp	loc_A092
; ---------------------------------------------------------------------------

loc_9FD3:
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.shottype], 2
		jnz	loc_A097
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 42), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 43), 6
		mov	text_default_fx, (6 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 44, 2, 6
		mov	text_default_fx, (15 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 46, 2, 6
		mov	text_default_fx, (6 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 48), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 49), 12
		mov	text_force_type_fast, 0
		push	(144 shl 16 or 332)
		push	44
		push	ds
		push	offset end_buf + (END_LINE_LEN * 50)

loc_A092:
		push	9
		call	graph_putsa_fx_with_typing

loc_A097:
		call	sub_9AD4
		pop	si
		pop	bp
		retn
sub_9B64	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_A09D	proc near
		push	bp
		mov	bp, sp
		push	si
		call	load_end_txt pascal, ds, offset aEnd2_txt
		call	_snd_load c, offset aEnd1_m, ds, SND_LOAD_SONG
		kajacall	KAJA_SONG_PLAY
		pop	cx
		mov	PaletteTone, 0
		call	far ptr	palette_show
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd01_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	palette_black_in pascal, 2
		call	frame_delay pascal, 40
		call	egc_quarter_put pascal, 0
		mov	text_default_fx, (15 or 2 shl 4)
		mov	text_force_type_fast, 1
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 0), 6
		call	frame_delay pascal, 20
		call	palette_black_out pascal, 1
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd03_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	egc_quarter_put pascal, 0
		call	palette_black_in pascal, 1
		ENDTEXT_PRINT_MUTIPLE_LINE 1, 3, 6
		call	egc_quarter_put pascal, 1
		ENDTEXT_PRINT_MUTIPLE_LINE 4, 6, 6
		call	egc_quarter_put pascal, 2
		ENDTEXT_PRINT_MUTIPLE_LINE 10, 2, 6
		call	egc_quarter_put pascal, 3
		ENDTEXT_PRINT_MUTIPLE_LINE 12 ,2, 6
		call	palette_entry_rgb pascal, ds, offset aEd03a_rgb
		call	far ptr	palette_show
		mov	text_default_fx, (9 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 14, 2, 6
		call	palette_black_out pascal, 2
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd04_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		graph_accesspage 0
		call	egc_quarter_put pascal, 0
		call	palette_black_in pascal, 2
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 16), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 17), 6
		mov	text_default_fx, (15 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 18, 2, 6
		call	egc_quarter_put pascal, 1
		mov	text_default_fx, (9 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 20, 2, 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 22), 6
		mov	text_default_fx, (9 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 23, 2, 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 25), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 26), 6
		call	frame_delay pascal, 10
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.shottype], 0
		jnz	loc_A4EC
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 27), 6
		call	frame_delay pascal, 30
		call	egc_quarter_put pascal, 2
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 28), 6
		call	egc_quarter_put pascal, 3
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 29), 6
		mov	text_default_fx, (9 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 30, 2, 6
		mov	text_default_fx, (15 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 32, 5, 6
		mov	text_default_fx, (9 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 37, 2, 6
		mov	text_default_fx, (15 or 2 shl 4)
		call 	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 39), 6
		call	palette_black_out pascal, 2
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd05_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	egc_quarter_put pascal, 0
		call	palette_black_in pascal, 2
		ENDTEXT_PRINT_MUTIPLE_LINE 40, 7, 6
		mov	text_force_type_fast, 0
		push	(144 shl 16 or 332)
		push	2Ch ; ','
		push	ds
		push	offset end_buf + (END_LINE_LEN * 47)
		jmp	loc_A869
; ---------------------------------------------------------------------------

loc_A4EC:
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.shottype], 1
		jnz	loc_A6B6
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 48), 6
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 49), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 50), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 51), 6
		call	frame_delay pascal, 30
		call	egc_quarter_put pascal, 2
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 52), 6
		call	egc_quarter_put pascal, 3
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 53), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 54), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 55), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 56), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 57), 6
		mov	text_default_fx, (9 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 58, 4, 6
		mov	text_default_fx, (15 or 2 shl 4)
		ENDTEXT_PRINT_MUTIPLE_LINE 62, 5, 6
		call	palette_black_out pascal, 2
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd05_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	egc_quarter_put pascal, 1
		call	palette_black_in pascal, 2
		ENDTEXT_PRINT_MUTIPLE_LINE 67, 2, 6
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 69), 12
		mov	text_force_type_fast, 0
		push	(144 shl 16 or 332)
		push	2Ch ; ','
		push	ds
		push	offset end_buf + (END_LINE_LEN * 70)
		jmp	loc_A869
; ---------------------------------------------------------------------------

loc_A6B6:
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 71), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 72), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 73), 6
		call	frame_delay pascal, 30
		call	egc_quarter_put pascal, 2
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 74), 6
		call	egc_quarter_put pascal, 3
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 75), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 76), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 77), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 78), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 79), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 80), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 81), 6
		mov	text_default_fx, (9 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 82), 6
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 83), 6
		call	palette_black_out pascal, 2
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd05_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	egc_quarter_put pascal, 2
		call	palette_black_in pascal, 2
		ENDTEXT_PRINT_MUTIPLE_LINE 84, 8, 6
		call	graph_putsa_fx_with_typing pascal, LARGE (144 shl 16 or 332), 44, ds, offset end_buf + (END_LINE_LEN * 92), 6
		mov	text_force_type_fast, 0
		push	(144 shl 16 or 332)
		push	44
		push	ds
		push	offset end_buf + (END_LINE_LEN * 93)

loc_A869:
		push	12
		call	graph_putsa_fx_with_typing
		call	sub_9AD4
		pop	si
		pop	bp
		retn
sub_A09D	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
;void pascal endft_btf_put(int x, int y, int index)
endft_btf_put	proc near

@@i		= word ptr -2
@@x		= word ptr  4
@@y		= word ptr  6
@@index		= word ptr  8

		enter	2, 0
		push	si
		push	di
		mov	si, [bp+@@index]
		mov	di, [bp+@@x]
		mov	[bp+@@i], 0
		jmp	short loc_A898
; ---------------------------------------------------------------------------

loc_A887:
		push	si
		push	[bp+@@y]
		push	di
		call	over_put_8
		inc	[bp+@@i]
		inc	di
		add	si, 16

loc_A898:
		cmp	[bp+@@i], 5
		jl	short loc_A887
		pop	di
		pop	si
		leave
		retn	6
endft_btf_put	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_A8A4	proc near
		push	bp
		mov	bp, sp
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 0
		push	1A000C0h
		push	27F010Fh
		call	grcg_boxfill
		call	grcg_off
		pop	bp
		retn
sub_A8A4	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
;void pascal rotrect(unsigned char angle, int slot, int rad)
rotrect	proc near

@@rad		= word ptr  4
@@slot		= word ptr  6
@@angle		= word ptr  8

		push	bp
		mov	bp, sp
		call	rotrect_animate pascal, [bp+@@angle], [bp+@@rad]
		call	egc_quarter_put_x_y pascal, (32 shl 16 or 100), [bp+@@slot] 
		call	frame_delay pascal, 4
		mov	PaletteTone, 100
		call	far ptr	palette_show
		pop	bp
		retn	6
rotrect	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_A8FA	proc near

@@g_str		= byte ptr -4

		enter	4, 0
		push	si
		push	di
		call	_snd_delay_until_measure stdcall, 6
		pop	cx
		xor	si, si
		jmp	short @@th02_logo_done?
; ---------------------------------------------------------------------------

@@th02_logo_put:
		call	endft_btf_put pascal, (432 shl 16) or 184, si
		call	frame_delay pascal, 4
		add	si, 5

@@th02_logo_done?:
		cmp	si, 5*11
		jl	short @@th02_logo_put
		call	_graph_putsa_fx c, 528, LARGE (192 or (15 or 2 shl 4) shl 16), offset aVer1_00, ds
		call	_snd_delay_until_measure stdcall, 8
		pop	cx
		mov	si, 184
		jmp	short @@scroll_down_logo_done?
; ---------------------------------------------------------------------------

@@scroll_down_logo:
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 0
		push	528
		lea	ax, [si+4]
		push	ax
		push	591
		lea	ax, [si+19]
		push	ax
		call	grcg_boxfill
		call	grcg_off
		call	endft_btf_put pascal, 432, si, 5*10
		push	ds
		push	offset aVer1_00	; "ver 1.00"
		push	15 or (2 shl 4)
		lea	ax, [si+8]
		push	ax
		push	528
		call	_graph_putsa_fx
		add	sp, 0Ah
		call	frame_delay pascal, 1
		add	si, 4

@@scroll_down_logo_done?:
		cmp	si, 368
		jl	short @@scroll_down_logo
	
; ---------------------------------------------------------------------------
	
		call	_snd_delay_until_measure stdcall, 9
		pop	cx
		mov	text_default_fx, (15 or 2 shl 4)
		call	graph_putsa_fx_with_typing pascal, LARGE (432 shl 16 or 192), 20, ds, offset aTh02_staff, 12
		call	_snd_delay_until_measure stdcall, 13
		pop	cx
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd06_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		graph_accesspage 0
		call	rotrect pascal, 4, 0, 41
		call	sub_A8A4
		call	_graph_putsa_fx c, 416, LARGE (192 or (15 or 2 shl 4) shl 16), offset aProgram_ZUN, ds
		call	_snd_delay_until_measure stdcall, 17
		pop	cx
		call	palette_entry_rgb pascal, ds, offset aEd06b_rgb
		call	far ptr	palette_show
		call	rotrect pascal, (-4 and 255), 2, 41
		call	_snd_delay_until_measure stdcall, 21
		pop	cx
		call	egc_quarter_put_x_y pascal, (32 shl 16 or 100), 3
		call	palette_entry_rgb pascal, ds, offset aEd06c_rgb
		call	far ptr	palette_show
		call	rotrect pascal, 4, 3, 41
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd07_pi, ds
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		graph_accesspage 0
		call	_snd_delay_until_measure stdcall, 25
		pop	cx
		call	sub_A8A4
		call	_graph_putsa_fx c, 416, LARGE (192 or (15 or 2 shl 4) shl 16), offset aGraphic_ZUN, ds
		call	_graph_putsa_fx c, 416, LARGE (224 or (15 or 2 shl 4) shl 16), offset aGraphic_1, ds
		call	_graph_putsa_fx c, 416, LARGE (240 or (15 or 2 shl 4) shl 16), offset aGraphic_2, ds
		call	palette_entry_rgb pascal, ds, offset aEd07a_rgb ; "ed07a.rgb"
		call	far ptr	palette_show
		call	rotrect pascal, (-4 and 255), 0, 41
		call	_snd_delay_until_measure stdcall, 29
		pop	cx
		call	palette_entry_rgb pascal, ds, offset aEd07b_rgb ; "ed07b.rgb"
		call	far ptr	palette_show
		call	rotrect pascal, 8, 1, 233
		call	_snd_delay_until_measure stdcall, 33
		pop	cx
		call	egc_quarter_put_x_y pascal, (32 shl 16 or 100), 2
		call	rotrect pascal, (-8 and 255), 2, 233
		call	_snd_delay_until_measure stdcall, 37
		pop	cx
		call	sub_A8A4
		call	_graph_putsa_fx c, 432, LARGE (192 or (15 or 2 shl 4) shl 16), offset aMUSIC_ZUN, ds
		call	palette_entry_rgb pascal, ds, offset aEd07b_rgb ; "ed07b.rgb"
		call	far ptr	palette_show
		call	rotrect pascal, 8, 3, 233
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd08_pi, ds
		call	_pi_slot_put c, 0, large 0
		graph_accesspage 0
		call	_snd_delay_until_measure stdcall, 41
		pop	cx
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		freePISlotLarge	0
		call	rotrect pascal, (-8 and 255), 0,  233
		call	_snd_delay_until_measure stdcall, 45
		pop	cx
		call	palette_entry_rgb pascal, ds, offset aEd08a_rgb ; "ed08a.rgb"
		call	far ptr	palette_show
		call	rotrect pascal, 12, 1, 41
		call	_snd_delay_until_measure stdcall, 49
		pop	cx
		call	sub_A8A4
		call	_graph_putsa_fx c, 416, LARGE (192 or (15 or 2 shl 4) shl 16), offset aTEST_PLAYER, ds
		call	_graph_putsa_fx c, 416, LARGE (224 or (15 or 2 shl 4) shl 16), offset aTEST_PLAYER_1, ds
		call	_graph_putsa_fx c, 416, LARGE (248 or (15 or 2 shl 4) shl 16), offset aTEST_PLAYER_2, ds
		call	_graph_putsa_fx c, 416, LARGE (272 or (15 or 2 shl 4) shl 16), offset aTEST_PLAYER_3, ds
		call	_graph_putsa_fx c, 416, LARGE (296 or (15 or 2 shl 4) shl 16), offset aTEST_PLAYER_4, ds
		call	palette_entry_rgb pascal, ds, offset aEd08b_rgb ; "ed08b.rgb"
		call	far ptr	palette_show
		call	rotrect pascal, (-12 and 255), 2, 41
		call	_snd_delay_until_measure stdcall, 53
		pop	cx
		call	palette_entry_rgb pascal, ds, offset aEd08c_rgb ; "ed08c.rgb"
		call	far ptr	palette_show
		call	rotrect pascal, 12, 3, 41
		call	_snd_delay_until_measure stdcall, 57
		pop	cx
		call	palette_black_out pascal, 4
		graph_accesspage 1
		call	_pi_slot_load c, 0, offset aEd09_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	graph_copy_page pascal, 0
		call	palette_black_in pascal, 4
		call	frame_delay pascal, 100
		graph_accesspage 1
		push	ds
		push	offset aThank_you_for_playing
		mov	al, text_default_fx
		cbw
		push	ax
		push	24 or (96 shl 16)
		call	_graph_putsa_fx
		add	sp, 0Ah
		call	text_fadein_effect c, 24, LARGE(96 or 21 shl 16)
		call	frame_delay pascal, 200
		graph_accesspage 1
		push	ds
		push	offset aTotal_score ; "Å@ç≈èIìæì_"
		mov	al, text_default_fx
		cbw
		push	ax
		push	64 or (128 shl 16)
		call	_graph_putsa_fx
		add	sp, 0Ah
		call	gaiji_score_put pascal, (192 shl 16) or 128, LARGE [_score]
		call	text_fadein_effect c, 64, LARGE(128 or 16 shl 16)
		call	frame_delay pascal, 100
		graph_accesspage 1
		push	ds
		push	offset aContinue ;	"ÉRÉìÉeÉBÉjÉÖÅ["
		mov	al, text_default_fx
		cbw
		push	ax
		push	64 or (160 shl 16)
		call	_graph_putsa_fx
		add	sp, 0Ah
		push	(256 shl 16) or 160
		les	bx, _resident
		mov	ax, es:[bx+mikoconfig_t.continues_used]
		add	ax, gb_0_
		push	ax
		push	15
		call	graph_gaiji_putc
		call	text_fadein_effect c, 64, LARGE(160 or 16 shl 16)
		call	frame_delay pascal, 100
		graph_accesspage 1
		push	ds
		push	offset aRank ; "Å@ ÉâÉìÉN"
		mov	al, text_default_fx
		cbw
		push	ax
		push	64 or (192 shl 16)
		call	_graph_putsa_fx
		add	sp, 0Ah
		push	(208 shl 16) or 192
		push	GAIJI_W
		push	ds
		mov	al, _rank
		cbw
		shl	ax, 3
		add	ax, offset _RANKS_CENTER
		push	ax
		push	15
		call	graph_gaiji_puts
		call	text_fadein_effect c, 64, LARGE(192 or 16 shl 16)
		call	frame_delay pascal, 100
		graph_accesspage 1
		push	ds
		push	offset aStart_lives ; "ÉvÉåÉCÉÑÅ[èâä˙"
		mov	al, text_default_fx
		cbw
		push	ax
		push	64 or (224 shl 16)
		call	_graph_putsa_fx
		add	sp, 0Ah
		push	(256 shl 16) or 224
		les	bx, _resident
		mov	al, es:[bx+mikoconfig_t.start_lives]
		mov	ah, 0
		add	ax, gb_1_
		push	ax
		push	15
		call	graph_gaiji_putc
		call	text_fadein_effect c, 64, LARGE(224 or 16 shl 16)
		call	frame_delay pascal, 100
		graph_accesspage 1
		push	ds
		push	offset aStart_bombs; " óÏåÇèâä˙êî"
		mov	al, text_default_fx
		cbw
		push	ax
		push	64 or (256 shl 16)
		call	_graph_putsa_fx
		add	sp, 0Ah
		push	(256 shl 16) or 256
		les	bx, _resident
		mov	al, es:[bx+mikoconfig_t.start_bombs]
		mov	ah, 0
		add	ax, gb_0_
		push	ax
		push	15
		call	graph_gaiji_putc
		call	text_fadein_effect c, 64, LARGE(256 or 16 shl 16)
		call	frame_delay pascal, 150
		graph_accesspage 1
		les	bx, _resident
		mov	di, es:[bx+mikoconfig_t.skill]
		cmp	di, 100
		jle	short loc_AEAC
		mov	di, 100
		jmp	short loc_AEB2
; ---------------------------------------------------------------------------

loc_AEAC:
		or	di, di
		jge	short loc_AEB2
		xor	di, di

loc_AEB2:
		push	ds
		push	offset aYour_rank ; "Ç†Ç»ÇΩÇÃòrëO"
		mov	al, text_default_fx
		cbw
		push	ax
		push	64 or (288 shl 16) 
		call	_graph_putsa_fx
		add	sp, 0Ah
		push	di
		push	ss
		lea	ax, [bp+@@g_str]
		push	ax
		call	sub_9846
		push	(192 shl 16) or 288
		push	GAIJI_W
		push	ss
		lea	ax, [bp+@@g_str]
		push	ax
		push	15
		call	graph_gaiji_puts
		cmp	di, 100
		jnz	short loc_AEEF
		xor	si, si
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AEEF:
		cmp	di, 90
		jl	short loc_AEF9
		mov	si, 1
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AEF9:
		cmp	di, 80
		jl	short loc_AF03
		mov	si, 2
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AF03:
		cmp	di, 70
		jl	short loc_AF17
		cmp	di, 77
		jnz	short loc_AF12
		mov	si, 3
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AF12:
		mov	si, 4
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AF17:
		cmp	di, 60
		jl	short loc_AF21
		mov	si, 5
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AF21:
		cmp	di, 50
		jl	short loc_AF2B
		mov	si, 6
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AF2B:
		cmp	di, 40
		jl	short loc_AF35
		mov	si, 7
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AF35:
		cmp	di, 30
		jl	short loc_AF3F
		mov	si, 8
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AF3F:
		cmp	di, 20
		jl	short loc_AF49
		mov	si, 9
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AF49:
		cmp	di, 10
		jl	short loc_AF53
		mov	si, 10
		jmp	short loc_AF56
; ---------------------------------------------------------------------------

loc_AF53:
		mov	si, 11

loc_AF56:
		mov	ax, si
		imul	ax, END_LINE_LEN
		add	ax, offset end_buf
		push	ds
		push	ax
		mov	al, text_default_fx
		cbw
		push	ax
		push	240 or (288 shl 16)
		call	_graph_putsa_fx
		add	sp, 0Ah
		call	text_fadein_effect c, 64, LARGE(288 or 6 shl 16)
		call	frame_delay pascal, 120
		call	text_fadein_effect c, 192, LARGE(288 or 24 shl 16)
		call	frame_delay pascal, 200
		graph_accesspage 1
		push	ds
		push	offset a1997_ZUN ; "ÇPÇXÇXÇVÅ@ÇyÇtÇm  (Amusement Makers)"
		mov	al, text_default_fx
		cbw
		push	ax
		push	64 or (352 shl 16)
		call	_graph_putsa_fx
		add	sp, 0Ah
		call	text_fadein_effect c, 64, LARGE(352 or 18 shl 16)
		call	_key_delay
		call	palette_black_out pascal, 5
		nopcall	sub_AFE7
		call	graph_clear
		pop	di
		pop	si
		leave
		retn
sub_A8FA	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_AFE7	proc far
		push	bp
		mov	bp, sp
		call	scoredat_is_extra_unlocked
		or	ax, ax
		jz	loc_B07D
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.continues_used], 0
		jnz	short loc_B07D
		call	_pi_slot_load c, 0, offset aAll_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	palette_black_in pascal, 2
		call	frame_delay pascal, 150
		call	_pi_slot_load c, 0, offset aBut_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	_key_delay
		call	palette_black_out pascal, 5

loc_B07D:
		pop	bp
		retf
sub_AFE7	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_B07F	proc far
		push	bp
		mov	bp, sp
		call	scoredat_is_extra_unlocked
		or	ax, ax
		jz	loc_B115
		mov	PaletteTone, 0
		call	far ptr	palette_show
		call	_pi_slot_load c, 0, offset aAll_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	palette_black_in pascal, 2
		call	frame_delay pascal, 150
		call	_pi_slot_load c, 0, offset aExtra_pi, ds
		call	_pi_slot_palette_apply stdcall, 0
		pop	cx
		call	_pi_slot_put c, 0, large 0
		freePISlotLarge	0
		call	_key_delay
		call	palette_black_out pascal, 5

loc_B115:
		pop	bp
		retf
sub_B07F	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; int __cdecl main(int _argc, const char **_argv, const	char **_envp)
public _main
_main		proc far

_argc		= word ptr  6
_argv		= dword	ptr  8
_envp		= dword	ptr  0Ch

		push	bp
		mov	bp, sp
		call	cfg_load
		or	ax, ax
		jz	loc_B1FE
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.stage], 7Fh
		jnz	loc_B1FE
		call	_game_init_main
		call	gaiji_backup
		call	gaiji_entry_bfnt stdcall, offset aMikoft_bft, ds
		call	_snd_pmd_resident
		call	_snd_mmd_resident
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.bgm_mode], 0
		jnz	short loc_B161
		mov	_snd_midi_active, 0
		jmp	short loc_B189
; ---------------------------------------------------------------------------

loc_B161:
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.bgm_mode], 1
		jnz	short loc_B173
		mov	_snd_midi_active, 0
		jmp	short loc_B184
; ---------------------------------------------------------------------------

loc_B173:
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.bgm_mode], 2
		jnz	short loc_B189
		mov	al, _snd_midi_possible
		mov	_snd_midi_active, al

loc_B184:
		call	_snd_determine_mode

loc_B189:
		graph_accesspage 0
		mov	dx, 0A4h
		out	dx, al
		call	super_entry_bfnt pascal, ds, offset aEndft_bft ; "endft.bft"
		call	frame_delay pascal, 100
		les	bx, _resident
		cmp	es:[bx+mikoconfig_t.rank], 4
		jz	short loc_B1C2
		cmp	es:[bx+mikoconfig_t.continues_used], 0
		jz	short loc_B1BA
		call	sub_9B64
		jmp	short loc_B1BD
; ---------------------------------------------------------------------------

loc_B1BA:
		call	sub_A09D

loc_B1BD:
		call	sub_A8FA
		jmp	short loc_B1C6
; ---------------------------------------------------------------------------

loc_B1C2:
		call	sub_B07F

loc_B1C6:
		mov	PaletteTone, 50
		call	far ptr	palette_show
		call	score_enter
		mov	PaletteTone, 0
		call	far ptr	palette_show
		call	gaiji_restore
		call	_game_exit
		pushd	0
		push	ds
		push	offset path	; "op"
		push	ds
		push	offset path	; "op"
		call	_execl
		add	sp, 0Ch

loc_B1FE:
		pop	bp
		retf
_main		endp

maine_01_TEXT	ends

; ===========================================================================

maine_02_TEXT	segment	word public 'CODE' use16
	extern _graph_putsa_fx:proc
	extern _key_delay:proc
	extern _vram_planes_set:proc
	extern _pi_slot_load:proc
	extern FRAME_DELAY:proc
	extern _input_sense:proc
	extern _game_exit:proc
	extern _snd_mmd_resident:proc
	extern _snd_determine_mode:proc
	extern _snd_pmd_resident:proc
	extern _snd_load:proc
	extern _game_init_main:proc
	extern _pi_slot_palette_apply:proc
	extern _pi_slot_put:proc
	extern _snd_kaja_interrupt:proc
	extern _snd_delay_until_measure:proc
maine_02_TEXT	ends

; ===========================================================================

maine_03_TEXT	segment	byte public 'CODE' use16
	extern CFG_LOAD:proc
maine_03_TEXT	ends

; ===========================================================================

maine_04_TEXT	segment	byte public 'CODE' use16
	extern SCOREDAT_IS_EXTRA_UNLOCKED:proc
	extern SCORE_ENTER:proc
maine_04_TEXT	ends

; ===========================================================================

maine_05_TEXT	segment	byte public 'CODE' use16
	extern EGC_START_COPY:proc
	extern ROTRECT_ANIMATE:proc
maine_05_TEXT	ends

	.data

include th02/strings/ranks_center[data].asm
unk_D030	db 50h dup(0)
label byte_D080 byte
	db 0AAh, 0AAh,  55h,  55h, 0AAh, 0AAh,  55h,  55h
	db 0AAh, 0AAh,  55h,  55h, 0AAh, 0AAh,  55h,  55h
	db 0AAh, 0AAh,  55h,  55h, 0AAh, 0AAh,  55h,  55h
	db 0AAh, 0AAh,  55h,  55h, 0AAh, 0AAh,  55h,  55h
	db  33h,  33h,  33h,  33h, 0CCh, 0CCh, 0CCh, 0CCh
	db  33h,  33h,  33h,  33h, 0CCh, 0CCh, 0CCh, 0CCh
	db  33h,  33h,  33h,  33h, 0CCh, 0CCh, 0CCh, 0CCh
	db  33h,  33h,  33h,  33h, 0CCh, 0CCh, 0CCh, 0CCh
	db 0CCh, 0CCh, 0CCh, 0CCh,  33h,  33h,  33h,  33h
	db 0CCh, 0CCh, 0CCh, 0CCh,  33h,  33h,  33h,  33h
	db 0CCh, 0CCh, 0CCh, 0CCh,  33h,  33h,  33h,  33h
	db 0CCh, 0CCh, 0CCh, 0CCh,  33h,  33h,  33h,  33h
aEnd3_txt	db 'end3.txt',0
aEnding_m	db 'ending.m',0
aEnd1_txt	db 'end1.txt',0
aEnd1_m		db 'end1.m',0
aEd01_pi	db 'ed01.pi',0
aEd02_pi	db 'ed02.pi',0
aEnd2_txt	db 'end2.txt',0
aEd03_pi	db 'ed03.pi',0
aEd03a_rgb	db 'ed03a.rgb',0
aEd04_pi	db 'ed04.pi',0
aEd05_pi	db 'ed05.pi',0
aVer1_00	db 'ver 1.00',0
aTh02_staff	db 'ïïñÇò^Å@Å@ÇrÇsÇ`ÇeÇe',0
aEd06_pi	db 'ed06.pi',0
aProgram_ZUN	db 'ÉvÉçÉOÉâÉÄÅ@Å@Å@ÇyÇtÇm',0
aEd06b_rgb	db 'ed06b.rgb',0
aEd06c_rgb	db 'ed06c.rgb',0
aEd07_pi	db 'ed07.pi',0
aGraphic_ZUN	db 'ÉOÉâÉtÉBÉbÉNÅ@ÇyÇtÇm',0
aGraphic_1	db 'Å@Å@Å@Å@Å@Å@Å@çÇïçì˙å¸',0
aGraphic_2	db 'Å@Å@Å@Å@ÅiÉIÅ[ÉãÉNÉäÉAâÊÅj',0
aEd07a_rgb	db 'ed07a.rgb',0
aEd07b_rgb	db 'ed07b.rgb',0
aMUSIC_ZUN	db 'ÇlÇtÇrÇhÇbÅ@Å@ÇyÇtÇm',0
aEd08_pi	db 'ed08.pi',0
aEd08a_rgb	db 'ed08a.rgb',0
aTEST_PLAYER	db 'ÇsÇdÇrÇsÅ@ÇoÇkÇ`ÇxÇdÇq',0
aTEST_PLAYER_1	db 'Å@Å@Å@Å@Ç©Ç®ÇÈ',0
aTEST_PLAYER_2	db 'Å@Å@Å@Å@ÇbÅ|Çv',0
aTEST_PLAYER_3	db 'Å@Å@ éRìcÅ@åbàÍòY',0
aTEST_PLAYER_4	db ' ÇªÇÃëºëÂê®ÇÃÇ›Ç»Ç≥ÇÒ',0
aEd08b_rgb	db 'ed08b.rgb',0
aEd08c_rgb	db 'ed08c.rgb',0
aEd09_pi	db 'ED09.pi',0
aThank_you_for_playing	db 'ÇsÇàÇÅÇéÇãÅ@ÇôÇèÇïÅ@ÇÜÇèÇíÅ@ÇêÇåÇÅÇôÇâÇéÇá',0
aTotal_score	db 'Å@ç≈èIìæì_',0
aContinue	db 'ÉRÉìÉeÉBÉjÉÖÅ[',0
aRank	db 'Å@ ÉâÉìÉN',0
aStart_lives	db 'ÉvÉåÉCÉÑÅ[èâä˙',0
aStart_bombs	db ' óÏåÇèâä˙êî',0
aYour_rank	db 'Ç†Ç»ÇΩÇÃòrëO',0
a1997_ZUN	db 'ÇPÇXÇXÇVÅ@ÇyÇtÇm  (Amusement Makers)',0
aAll_pi		db 'all.pi',0
aBut_pi		db 'but.pi',0
aExtra_pi	db 'extra.pi',0
aMikoft_bft	db 'MIKOFT.bft',0
aEndft_bft	db 'endft.bft',0
; char path[]
path		db 'op',0
include libs/master.lib/bfnt_id[data].asm
include libs/master.lib/clip[data].asm
include libs/master.lib/edges[data].asm
include libs/master.lib/fil[data].asm
include libs/master.lib/dos_ropen[data].asm
include libs/master.lib/gaiji_backup[data].asm
include libs/master.lib/gaiji_entry_bfnt[data].asm
include libs/master.lib/grp[data].asm
include libs/master.lib/pal[data].asm
include libs/master.lib/pf[data].asm
include libs/master.lib/sin8[data].asm
include libs/master.lib/tx[data].asm
include libs/master.lib/version[data].asm
include libs/master.lib/vs[data].asm
include libs/master.lib/mem[data].asm
include libs/master.lib/super_entry_bfnt[data].asm
include libs/master.lib/superpa[data].asm
public _key_delay_groups
_key_delay_groups	db 5, 3, 0
		db 0
include th02/formats/pfopen[data].asm
extern _rank:byte

	.data?

end_buf	db 100 dup(END_LINE_LEN dup(?))
text_default_fx	db ?
text_force_type_fast	db ?
include libs/master.lib/clip[bss].asm
include libs/master.lib/fil[bss].asm
include libs/master.lib/pal[bss].asm
include libs/master.lib/vs[bss].asm
include libs/master.lib/vsync[bss].asm
include libs/master.lib/mem[bss].asm
include libs/master.lib/superpa[bss].asm
include th01/hardware/vram_planes[bss].asm
include th02/formats/pi_slots[bss].asm
include libs/master.lib/pfint21[bss].asm
include th02/hardware/input_sense[bss].asm
include th02/snd/snd[bss].asm
include th02/snd/load[bss].asm
extern _resident:dword
extern _score:dword

		end
